---
abstract: 'view and manipulate ascii art and manipulation files created in JavE.'
author:
  - 'osfameron - osfameron@cpan.org'
build_requires:
  ExtUtils::MakeMaker: '0'
configure_requires:
  ExtUtils::MakeMaker: '0'
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.98, CPAN::Meta::Converter version 2.141170'
license: unknown
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Text-JavE
no_index:
  directory:
    - t
    - inc
requires:
  Test::More: '1.001003'
version: v0.0.3
